### ISSUE TITLE
ResourceNotFound: naoqi_driver

### ISSUE THREAD

**Issue by jokla** [ros-aldebaran/romeo_robot#7]
Hi!

I am trying to work with ROS with Romeo. Ubuntu 14.04 and Indigo.

When I launch:
`roslaunch romeo_bringup romeo_full.launch`
I get this error:
`ResourceNotFound: naoqi_driver`

In my catkin_ws I have the package romeo_robot (I prefer to build it from source).

I installed using synaptic the following packages:
ros-indigo-naoqi-bridge-msgs
ros-indigo-naoqi-driver-py
ros-indigo-naoqi-sensors-py

But I cannot find the package `ros-indigo-naoqi-driver`, there is just the jade version... Should I build everything from source?
If I try to build it from source (https://github.com/ros-naoqi/naoqi_driver) I get some errors (related to [the problem in libqi ](https://github.com/ros-naoqi/libqi-release/issues/3) )

What should I do?

Thank you very much!

Giovanni

**Comment by mikaelarguedas** [comment]
Hi Giovanni,

Yes since the upgrade of libqi, naoqi driver has trouble compiling on the ros buildfarm this is why you cannot `apt-get install ros-indigo-naoqi_driver`

I you want to use the python equivalent you'll have to launch `roslaunch romeo_bringup romeo_full_py.launch`. The behaviour should be the same.

The other alternative is to compile libqi then naoqi_driver from sources.

Hope this helps,

Mikael

**Comment by jokla** [comment]
Thanks for the answer Mikael,

I will try and let you know.

Giovanni

**Comment by jokla** [comment]
The pack `ros-indigo-naoqi-driver` is available now. Thanks!
